import type { Copy } from "./types";

const en: Copy = {
  lang: "en",
  meta: {
    title: "Lantern IDE — see how far an edit reaches before the agent makes it",
    description: "An open-source AI code editor that hands the model only the code a question needs, and shows the callers, tests and risk of every agent edit before you approve it. Bring your own model.",
  },
  nav: { github: "GitHub", download: "Download", other: "한국어", otherHref: "/", skip: "Skip to content" },
  steps: { request: "Request", context: "Context", read: "Read", impact: "Impact", isolate: "Isolate", commit: "Commit" },
  chips: { context: "context", read: "read", edited: "edited", risk: { low: "risk low", medium: "risk medium", high: "risk high" } },
  hero: {
    title: ["Before the agent edits,", "see how far the change reaches."],
    lede: "Lantern IDE hands the model only the code each question needs, and for every edit the agent proposes it shows who calls that code, which tests cover it, and how risky it is, before you approve. You choose the model.",
    downloadFor: { windows: "Download for Windows", mac: "Download for macOS", linux: "Download for Linux" },
    releases: "Get it from Releases",
    otherOs: "Other platforms",
    github: "Read the code on GitHub",
    note: "Open source · Apache-2.0 · No telemetry · Beta",
  },
  source: (files, edges, commit) => `The map behind this page is the Lantern repository itself: ${files} files, ${edges} links (commit ${commit}).`,
  request: {
    title: "Ask in Korean, and it still finds the English code.",
    body: "The context engine first turns the question into search terms. A general developer glossary widens 중복 (“duplicate”) into duplicate and dedupe, so code without Korean comments still matches. The request below is the one this page follows.",
    label: "Task",
    asked: "Words from the question",
    expanded: "Added by the glossary",
  },
  context: {
    title: "Only the code it needs, within budget.",
    body: "It ranks code from the symbol graph, full-text search, files that changed together in git, and project notes, then trims to the token budget you set. The inspector shows every file it sent, and why.",
    files: (n) => `${n} files picked for this question`,
    more: (n) => `${n} more`,
    budget: (used, budget, ms) => `${used} / ${budget} tokens · assembled in ${ms} ms`,
    evidenceTitle: "How many answer files each approach retrieves at the same budget",
    evidence: [
      { label: "Answer files retrieved (mean recall)", grep: "24%", lantern: "67%" },
      { label: "Questions with at least one answer file", grep: "35%", lantern: "90%" },
    ],
    grep: "Keyword search",
    lantern: "Lantern",
    condition: "Measured on one private project (1,772 code files, 20 hand-labelled questions, 8,000-token budget). A public benchmark on an open-source codebase is in progress.",
  },
  read: {
    title: "What the agent read stays on the map.",
    body: "Context sent to the model is teal, files the agent opened itself get a dashed ring, and edited files are indigo. Each task keeps its footprint, so you can come back later and see what it looked at before deciding.",
    legend: { context: "context sent", read: "read", edited: "edited" },
    log: { read: "Read the caller first", edit: "Proposing an edit" },
  },
  impact: {
    title: "Before you approve, see how far this one line reaches.",
    body: "For every proposed edit it finds the functions that change, then counts who calls them, who calls those callers, the tests in range, and files that usually change together. These numbers were computed on the Lantern repository when this page was built.",
    card: "Edit file",
    sample: "Sample edit",
    head: "Impact radius",
    direct: "direct callers",
    indirect: "indirect callers",
    files: "files",
    noTests: "No tests",
    tests: (n) => `${n} tests`,
    apply: "Apply",
    deny: "Deny",
    noTestsNote: "“No tests” means there is no separate test file in range. This function is only covered by unit tests inside its own file.",
    shot: "The real app: approval card with impact radius and Show on map",
  },
  isolate: {
    title: "Isolate a task, and your project stays untouched until you apply.",
    body: "Each task can get its own git worktree, and the agent edits only there. When it finishes you review the changes and apply them to the project or discard them. Undo asks first if files changed elsewhere in the meantime.",
    space: "Workspace",
    sample: "Sample",
    changed: "1 file changed",
    apply: "Apply to project",
    discard: "Discard",
  },
  commit: {
    title: "Many repositories, one view.",
    body: "It finds every git repository under the folder you open and shows each one’s branch, remote and changes. Fetch, pull, push, commit history and branch switching included. Pull only fast-forwards; if your branch has diverged, it tells you instead of merging.",
    sample: "Sample workspace",
    repos: [
      { name: "api", branch: "main", sync: "↑1", changes: 2 },
      { name: "web", branch: "feat/search", sync: "", changes: 5 },
      { name: "infra", branch: "main", sync: "↓3", changes: 0 },
      { name: "docs", branch: "main", sync: "", changes: 0 },
    ],
    actions: ["Fetch", "Pull", "Push", "History", "Branches"],
  },
  models: {
    title: "You pick the model, and you can see everything it was sent.",
    body: "Lantern doesn’t sell a model. Connect the API key you already use, or a local model on your machine.",
    rows: [
      { term: "Anthropic", text: "Claude (API key)" },
      { term: "OpenAI-compatible", text: "OpenAI, OpenRouter, vLLM, or any OpenAI-style endpoint" },
      { term: "Local", text: "Ollama, LM Studio. Your code never leaves the machine" },
    ],
    plain: ["No hidden system prompt", "No telemetry", "API keys in the OS credential store", "Monthly cost limit"],
  },
  cannot: {
    title: "What it can’t do yet",
    body: "This is a beta built by one person. Worth knowing before you try it.",
    rows: [
      { term: "Code signing", text: "Not yet. On Windows, SmartScreen warns you; choose “More info → Run anyway”." },
      { term: "macOS · Linux", text: "They build and pass tests, but haven’t been used day to day. macOS isn’t notarized, so you have to allow it the first time." },
      { term: "Merges · conflicts", text: "No UI. If a pull diverges, choose merge or rebase in the terminal." },
      { term: "Extensions", text: "VS Code extensions don’t run. It connects language servers (TypeScript, Rust, Python)." },
      { term: "Public benchmark", text: "Not yet. The recall numbers above come from one private project." },
    ],
  },
  close: {
    title: "Open a project you know well, and hand it one small change.",
    body: "Before approving, read the impact radius on the card and press Show on map. Tell us what worked and what got in the way; it shapes the next beta.",
    os: [
      { os: "windows", name: "Windows 10 · 11", detail: "x64 installer", status: "Tested", tested: true },
      { os: "mac", name: "macOS 11+", detail: "Apple Silicon · Intel", status: "Untested", tested: false },
      { os: "linux", name: "Linux", detail: "AppImage · deb", status: "Untested", tested: false },
    ],
    github: "View on GitHub",
    feedback: "Send beta feedback",
    untested: "Untested",
  },
  footer: { license: "Open source, Apache-2.0", made: "Lantern IDE", lang: "한국어", langHref: "/" },
};

export default en;
