import type { Copy } from "./types";

const ko: Copy = {
  lang: "ko",
  meta: {
    title: "Lantern IDE — 에이전트가 고치기 전에, 어디까지 닿는지",
    description: "필요한 코드만 골라 AI에 건네고, 에이전트의 수정마다 호출하는 곳·테스트·위험도를 승인 전에 보여주는 오픈소스 AI 코드 편집기. 모델은 직접 고릅니다.",
  },
  nav: { github: "GitHub", download: "받기", other: "English", otherHref: "/en/", skip: "본문으로 건너뛰기" },
  steps: { request: "요청", context: "맥락", read: "읽기", impact: "영향", isolate: "격리", commit: "커밋" },
  chips: { context: "맥락", read: "읽음", edited: "수정", risk: { low: "위험도 낮음", medium: "위험도 보통", high: "위험도 높음" } },
  hero: {
    title: ["에이전트가 고치기 전에,", "어디까지 닿는지 먼저 봅니다."],
    lede: "Lantern IDE는 질문마다 필요한 코드만 골라 AI에 건네고, 에이전트가 내놓는 수정마다 그 코드를 부르는 곳·테스트·위험도를 승인 전에 보여주는 코드 편집기입니다. 모델은 직접 고릅니다.",
    downloadFor: { windows: "Windows용 받기", mac: "macOS용 받기", linux: "Linux용 받기" },
    releases: "릴리스에서 받기",
    otherOs: "다른 운영체제",
    github: "GitHub에서 코드 보기",
    note: "오픈소스 · Apache-2.0 · 사용 통계를 수집하지 않습니다 · 베타",
  },
  source: (files, edges, commit) => `뒤의 지도는 Lantern 저장소 자체입니다. 파일 ${files}개, 연결 ${edges}개 (커밋 ${commit})`,
  request: {
    title: "한국어로 물어도, 영어 코드를 찾습니다.",
    body: "요청을 받으면 맥락 엔진이 먼저 질문을 검색어로 바꿉니다. 일반 개발 용어 사전이 ‘중복’을 duplicate, dedupe로 넓혀서, 한국어 주석이 없는 코드도 찾습니다. 아래 요청이 이 페이지가 따라가는 예시 작업입니다.",
    label: "작업 요청",
    asked: "질문에 쓴 말",
    expanded: "사전이 넓힌 말",
  },
  context: {
    title: "필요한 코드만, 예산 안에서.",
    body: "심볼 그래프, 전문 검색, git에서 함께 바뀌던 파일, 프로젝트 메모를 합쳐 순위를 매기고, 정한 토큰 예산을 넘지 않게 잘라 붙입니다. 무엇을 왜 넣었는지는 인스펙터에서 전부 보입니다.",
    files: (n) => `이 질문에 고른 파일 ${n}개`,
    more: (n) => `외 ${n}개`,
    budget: (used, budget, ms) => `${used} / ${budget} 토큰 · 조립 ${ms}ms`,
    evidenceTitle: "같은 예산에서 정답 파일을 몇 개 가져오나",
    evidence: [
      { label: "정답 파일 적중률 (평균)", grep: "24%", lantern: "67%" },
      { label: "정답 파일을 하나라도 가져온 질문", grep: "35%", lantern: "90%" },
    ],
    grep: "키워드 검색",
    lantern: "Lantern",
    condition: "비공개 프로젝트 하나(코드 파일 1,772개, 직접 정한 질문 20개, 예산 8,000토큰)에서 잰 값입니다. 공개 코드베이스로 만든 벤치마크를 준비하고 있습니다.",
  },
  read: {
    title: "에이전트가 무엇을 읽었는지 지도에 남습니다.",
    body: "보낸 맥락은 청록, 에이전트가 직접 연 파일은 점선 고리, 고친 파일은 남색으로 칠합니다. 작업마다 발자취가 쌓여서, 이 작업이 무엇을 보고 결정했는지 나중에도 다시 볼 수 있습니다.",
    legend: { context: "AI에 보낸 맥락", read: "읽음", edited: "수정" },
    log: { read: "호출하는 쪽을 먼저 읽었습니다", edit: "수정을 제안합니다" },
  },
  impact: {
    title: "승인하기 전에, 이 한 줄이 어디까지 닿는지.",
    body: "수정 제안마다 바뀌는 함수를 찾아서 그것을 부르는 곳, 그 호출자를 부르는 곳, 영향 범위의 테스트, 함께 바뀌던 파일을 셉니다. 아래 수치는 이 페이지를 만들 때 Lantern 저장소에서 실제로 계산했습니다.",
    card: "파일 수정",
    sample: "예시 수정",
    head: "영향 반경",
    direct: "직접 호출",
    indirect: "간접 호출",
    files: "파일에 걸침",
    noTests: "테스트 없음",
    tests: (n) => `테스트 ${n}`,
    apply: "적용",
    deny: "거절",
    noTestsNote: "‘테스트 없음’은 영향 범위에 따로 떨어진 테스트 파일이 없다는 뜻입니다. 이 함수는 같은 파일 안의 단위 테스트로만 확인됩니다.",
    shot: "실제 앱 화면: 승인 카드와 영향 반경, 지도에서 보기",
  },
  isolate: {
    title: "격리해서 맡기면, 적용하기 전까지 프로젝트는 그대로입니다.",
    body: "작업마다 git worktree를 따로 만들어 에이전트가 거기서만 고칩니다. 끝나면 바뀐 내용을 보고 프로젝트에 적용하거나 버립니다. 되돌리기는 그 사이 다른 곳에서 바뀐 파일이 있으면 먼저 묻습니다.",
    space: "작업 공간",
    sample: "예시",
    changed: "파일 1개 바뀜",
    apply: "프로젝트에 적용",
    discard: "버리기",
  },
  commit: {
    title: "저장소가 여럿이어도 한 화면에서.",
    body: "연 폴더 아래의 git 저장소를 모두 찾아 저장소마다 브랜치·원격·변경을 보여줍니다. 가져오기·풀·푸시, 커밋 이력, 브랜치 전환까지 합니다. 풀은 앞으로 감기만 하고, 갈라졌으면 병합하지 않고 알려 줍니다.",
    sample: "예시 작업 폴더",
    repos: [
      { name: "api", branch: "main", sync: "↑1", changes: 2 },
      { name: "web", branch: "feat/search", sync: "", changes: 5 },
      { name: "infra", branch: "main", sync: "↓3", changes: 0 },
      { name: "docs", branch: "main", sync: "", changes: 0 },
    ],
    actions: ["가져오기", "풀", "푸시", "커밋 이력", "브랜치"],
  },
  models: {
    title: "모델은 직접 고르고, 보낸 것은 전부 보입니다.",
    body: "Lantern은 모델을 팔지 않습니다. 쓰던 API 키나 컴퓨터 안의 로컬 모델을 연결합니다.",
    rows: [
      { term: "Anthropic", text: "Claude (API 키)" },
      { term: "OpenAI 호환", text: "OpenAI, OpenRouter, vLLM 등 OpenAI 형식 주소" },
      { term: "로컬", text: "Ollama, LM Studio. 코드가 컴퓨터 밖으로 나가지 않습니다" },
    ],
    plain: ["숨은 시스템 프롬프트 없음", "사용 통계 수집 없음", "API 키는 운영체제 자격 증명 저장소에", "월 비용 한도"],
  },
  cannot: {
    title: "아직 못 하는 것",
    body: "혼자 만드는 베타입니다. 쓰기 전에 알아 두면 좋은 것들입니다.",
    rows: [
      { term: "코드 서명", text: "아직 없습니다. Windows에서 SmartScreen 경고가 뜨면 ‘추가 정보 → 실행’을 눌러야 합니다." },
      { term: "macOS · Linux", text: "빌드와 테스트는 통과하지만 실제로 써 보지 않았습니다. 공증 전이라 macOS는 처음 열 때 허용이 필요합니다." },
      { term: "병합 · 충돌 해결", text: "화면이 없습니다. 풀이 갈라지면 터미널에서 병합이나 리베이스를 고릅니다." },
      { term: "확장 기능", text: "VS Code 확장은 쓸 수 없습니다. 언어 서버(TypeScript, Rust, Python)만 연결합니다." },
      { term: "공개 벤치마크", text: "아직 없습니다. 위의 적중률은 비공개 프로젝트 하나로 잰 값입니다." },
    ],
  },
  close: {
    title: "잘 아는 프로젝트를 열고, 작은 수정 하나를 맡겨 보세요.",
    body: "승인하기 전에 카드의 영향 반경을 보고, ‘지도에서 보기’를 눌러 보세요. 무엇이 좋았고 무엇이 막혔는지 알려 주시면 다음 베타에 반영합니다.",
    os: [
      { os: "windows", name: "Windows 10 · 11", detail: "x64 설치 파일", status: "확인됨", tested: true },
      { os: "mac", name: "macOS 11 이상", detail: "Apple Silicon · Intel", status: "실사용 확인 전", tested: false },
      { os: "linux", name: "Linux", detail: "AppImage · deb", status: "실사용 확인 전", tested: false },
    ],
    github: "GitHub에서 보기",
    feedback: "베타 후기 보내기",
    untested: "실사용 확인 전",
  },
  footer: { license: "Apache-2.0 오픈소스", made: "Lantern IDE", lang: "English", langHref: "/en/" },
};

export default ko;
